# Generated by Django 6.0.3 on 2026-04-07 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='员工姓名')),
                ('job', models.CharField(choices=[('MR', '部门经理'), ('CE', '普通职员'), ('PR', '总裁')], default='CE', max_length=2, verbose_name='员工姓名')),
                ('entry_date', models.DateField(default=datetime.date(2026, 4, 7), verbose_name='入职时间')),
                ('sla', models.IntegerField(verbose_name='级别薪资')),
                ('bonus', models.SmallIntegerField(default=0, verbose_name='津贴')),
                ('is_leave', models.BooleanField(default=False, verbose_name='是否离职')),
            ],
            options={
                'verbose_name': '员工表',
                'verbose_name_plural': '员工表',
                'db_table': 't_emp',
                'ordering': ['id'],
            },
        ),
    ]
