# Generated by Django 6.0.3 on 2026-04-23 12:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='员工姓名')),
                ('job', models.CharField(choices=[('MR', '部门经理'), ('CE', '普通职员'), ('PR', '总裁')], default='CE', max_length=2, verbose_name='员工姓名')),
                ('entry_date', models.DateField(default=datetime.date(2026, 4, 23), verbose_name='入职时间')),
                ('sal', models.IntegerField(verbose_name='级别薪资')),
                ('bonus', models.SmallIntegerField(default=0, verbose_name='津贴')),
                ('is_leave', models.BooleanField(default=False, verbose_name='是否离职')),
                ('dept', models.BooleanField(default=False, verbose_name='所在部门')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '员工表',
                'verbose_name_plural': '员工表',
                'db_table': 't_emp',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='部门名称')),
                ('address', models.CharField(blank=True, max_length=110, unique=True, verbose_name='部门地址')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo1.deptmodel')),
            ],
            options={
                'verbose_name': '部门表',
                'verbose_name_plural': '部门表',
                'db_table': 't_demp',
                'ordering': ['id'],
            },
        ),
    ]
