# Generated by Django 6.0.3 on 2026-04-08 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='sla',
            new_name='sal',
        ),
        migrations.AlterField(
            model_name='employee',
            name='entry_date',
            field=models.DateField(default=datetime.date(2026, 4, 8), verbose_name='入职时间'),
        ),
    ]
