# Generated by Django 6.0.3 on 2026-04-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptmodel',
            name='address',
            field=models.CharField(blank=True, max_length=110, null=True, unique=True, verbose_name='部门地址'),
        ),
    ]
