# Generated by Django 6.0.3 on 2026-04-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='姓名')),
                ('last_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='姓')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': '人员表',
                'verbose_name_plural': '人员表',
                'db_table': 't_person',
                'ordering': ['id'],
            },
        ),
    ]
