# Generated by Django 6.0.3 on 2026-04-07 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='create_time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personmodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
