# Generated by Django 6.0.3 on 2026-04-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0002_personmodel_create_time_personmodel_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='create_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
